stages:
  - compile
  - test

variables:
  DEFAULT_IMAGE: eclipse-temurin:25-jdk-alpine

# TODO cache dependencies in container
compile:
  stage: compile
  image: $DEFAULT_IMAGE
  script:
    - ./gradlew compileJava
    - ./gradlew compileTestJava

test:
  stage: test
  image: $DEFAULT_IMAGE
  artifacts:
    reports:
      junit:
        - build/test-results/test/TEST-*.xml
  services:
    - name: docker:29-dind
      command:
        - "--tls=false"
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: "overlay2"
  script:
    - ./gradlew test