### Create Game Studio
// werkt niet omdat er geen manier is om via hier aan de access token te geraken
POST http://localhost:8080/api/gamestudio
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "Epic Games Studio",
  "description": "We create amazing indie games",
  "IBAN": "BE68539007547034"
}

> {% 
client.global.set("studioId", response.body.id)
 %}

### Create Game
POST http://localhost:8080/api/games
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "studioId": "{{studioId}}",
  "title": "Tic-Tac Toe",
  "description": "Tic-Tac-Toe is a simple two-player game played on a 3×3 grid. Players take turns marking spaces—one as X, the other as O—with the goal of placing three of their symbols in a row horizontally, vertically, or diagonally.",
  "price": 2.54,
  "gameUrl": "https://hub.example.com/games/tic-tac-toe",
  "imageUrl": "https://static.vecteezy.com/system/resources/previews/027/141/194/large_2x/tic-tac-toe-illustration-design-free-png.png",
  "genre": "ABSTRACT"
}


### Create Game
POST http://localhost:8080/api/notification