### Start game
POST http://localhost:8080/api/lobbies/singleplayer/start
Content-Type: application/json

{
  "playerId": "8f14e45f-ea07-4f5b-9bdd-66e123abcf02",
  "gameId": "1b2d89fa-bd59-4873-b568-8df26c3a047c"
}

###

POST http://localhost:8080/api/analytics/game/1b2d89fa-bd59-4873-b568-8df26c3a047c/achievement/WE LOVE THIS SHIZZLE/user/ed7b6a30-a12f-4ae5-9d25-b1ea51c89840