spring.jpa.hibernate.ddl-auto=create

spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false

spring.datasource.url=jdbc:postgresql://archportal-app_postgres-1:5432/postgres
spring.datasource.username=user
spring.datasource.password=password