# Hibernate & DB
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false
spring.flyway.validate-on-migrate=false
spring.sql.init.data-locations=classpath:sql/game-service-data.sql

spring.datasource.url=jdbc:postgresql://archportal-app-postgres-1:5432/postgres
spring.datasource.username=user
spring.datasource.password=password

# OAuth2 Keycloak prod
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost/auth/realms/ArchPortal
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://archportal-idp-keycloak-1:8080/auth/realms/ArchPortal/protocol/openid-connect/certs

# Flyway & mollie prod
mollie.redirect.url=http://localhost/payment-return
model.provider=ollama