spring.application.name=ArchPortal

spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=none

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/auth/realms/ArchPortal
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/auth/realms/ArchPortal/protocol/openid-connect/certs

mollie.api.key=test_VM7rVdGQTVmNycvvb4ARDNsJa4mpWT