spring.application.name=ArchPortal
spring.config.import=classpath:./secret.properties

spring.datasource.url=jdbc:postgresql://localhost:5443/postgres
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=create


