# Hibernate & DB
spring.jpa.hibernate.ddl-auto=create-drop

spring.config.import=classpath:secret.properties

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.data-locations=classpath:sql/game-service-data.sql

spring.datasource.url=jdbc:postgresql://localhost:5443/postgres
spring.datasource.username=user
spring.datasource.password=password

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user
spring.rabbitmq.password=password

# Flyway uitschakelen in dev indien je H2 gebruikt voor tests
spring.flyway.enabled=false